repos:
    -   repo: https://github.com/ambv/black
        rev: 19.10b0
        hooks:
            -   id: black
                language_version: python3.6
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
            -   id: check-yaml
            -   id: check-toml
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
            -   id: flake8
                additional_dependencies: [
                    'flake8-docstrings'#, 'darglint', 'pydocstyle<4.0'
                ]
            -   id: check-symlinks
            -   id: name-tests-test
            -   id: requirements-txt-fixer
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.740
        hooks:
            -   id: mypy
                args: [--no-strict-optional, --ignore-missing-imports]
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
            -   id: isort
#    -   repo: https://github.com/PyCQA/bandit
#        rev: 1.6.2
#        hooks:
#        - id: bandit
