repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -    id: flake8
         additional_dependencies: [
             'flake8-docstrings'#, 'darglint', 'pydocstyle<4.0'
         ]
